export const BASEURL = 'http://localhost:8000'

export enum API {
    FRIENDS = 'api/friends/',
    FEED = 'api/feed/',
    PROFILE = 'api/profile/',
    REPOST = 'api/repost/',
    GROUP = 'api/group/',
    LOGIN = 'api/auth/login/',
    REGISTRATION = 'api/auth/register/',
    LOGOUT = 'api/auth/logout',
    REFRESH = 'api/auth/refresh/',
    NOTIFICATIONS = 'api/notifications/',
    ME = 'api/me/',
    POSTS ='api/posts/',
    CHILD_COMMENTS = 'api/child_comments/',
    ROOT_COMMENTS = 'api/root_comments/',
    COMMENT = 'api/comments/',
    MESSENGER = 'api/message',
    FILES = '/files-upload',
    UPCOMING_BIRTHDAYS = 'api/upcoming-birth-day/',
    USERS = 'api/users/',
    AUTOCOMPLETE = 'api/users/autocomplete/',
    GALLERY = 'api/gallery/',
}
